### ISSUE TITLE
空白页面

### ISSUE THREAD

**Issue by linsui** [ivysrono/Fennec-Pure-Zhihu#1]
首先感谢你的插件 :+1:
似乎是这几天出现的问题，打开知乎问题页面后，会在只显示第一个回答的状态卡很久然后变成空白页面。

**Comment by ivysrono** [comment]
给个准确的地址和环境。

**Comment by linsui** [comment]
Fennec 67.0.3 
https://www.zhihu.com/question/327785364
这是我从知乎日报找的一个问题页面。似乎知乎首页比较稳定。

**Comment by linsui** [comment]
从知乎首页进入也没问题，但从知乎日报进入就会出现空白页面
https://daily.zhihu.com/story/9713137

**Comment by ivysrono** [comment]
确认问题。直接输入网址可以重现。麻烦提供更多信息，如有没有不出现这个问题的页面。

**Comment by linsui** [comment]
暂时没有，刚发现知乎首页进入的是回答页面。所以我猜所有问题页面都有问题。 :joy:

**Comment by ivysrono** [comment]
我最快要下周末才有空来修，欢迎 PR.

**Comment by linsui** [comment]
情况发生了变化，不会出现空白页面，而是只能查看前三个回答。 :joy:

**Comment by ivysrono** [comment]
哎，这三天两头改，是天意我等戒掉逼乎？

**Comment by linsui** [comment]
说不定以电脑版页面为基础还更稳定一些 :joy: 基本只用 CSS 就行

**Comment by ivysrono** [comment]
周末来研究下……生与死，这是个问题/(ㄒoㄒ)/~~

**Comment by ivysrono** [comment]
昨天看了下，感觉变化很大，有放弃维护的冲动。

**Comment by linsui** [comment]
:smile: 不如退乎吧。现在的状态也可用。

**Comment by ivysrono** [comment]
看到某乎融资某度的消息，退乎似乎才是明智之举。

**Comment by ivysrono** [comment]
本项目已失效并于2019中元节正式放弃维护！
